### ISSUE TITLE
Error with this.state.pan

### ISSUE THREAD

**Issue by CyberKronos** [brentvatne/react-native-animated-demo-tinder#10]
The reset state function:

_resetState() {
    this.state.pan.setValue({x: 0, y: 0});
    this.state.enter.setValue(0);
    this._goToNextPerson();
    this._animateEntrance();
}

yields "undefined is not an object (evaluating \'this.state.pan\')" after swiping away the first card.

Anything I am missing?

**Comment by mjason** [comment]
change your code

```
if (Math.abs(this.state.pan.x._value) > SWIPE_THRESHOLD) {
          Animated.decay(this.state.pan, {
            velocity: {x: velocity, y: vy},
            deceleration: 0.98
          }).start(this._resetState.bind(this))
        } else {
          Animated.spring(this.state.pan, {
            toValue: {x: 0, y: 0},
            friction: 4
          }).start()
        }
```

**Comment by CyberKronos** [comment]
where are you adding this?
to the _resetState() ?

**Comment by CyberKronos** [comment]
@mjason Thank you very much! it works!
