### ISSUE TITLE
Playing nice with Scroll View

### ISSUE THREAD

**Issue by tgoldenberg** [brentvatne/react-native-animated-demo-tinder#12]
I found this really helpful, so thanks for all your contributions! One thing I noticed is that if I style the component for portrait view and then switch to landscape view, my contents don't fit in that view. So I tried implementing ScrollView to make it play nice with the landscape view, but that makes the swipe events much harder and buggier. Any suggestion on how you would handle the situation? Thanks!

**Comment by tgoldenberg** [comment]
So I got it to work - if anyone else needs this, I set `scrollEnabled` on the ScrollView to be set to `this.state.scroll`. I start with the `scroll` set to `true`, in the `panResponderRelease` function I set it to false, and in the `_reset` function I set back to true. That seems to work fine.

**Comment by tgoldenberg** [comment]
Hi @brentvatne, curious what your approach would be for using Scroll View (up and down) with this. I tried mixing the two but it feels kind of choppy on my device. Any suggestions?

**Comment by danleveille** [comment]
@tgoldenberg Having the same issue here. Did you find a good solution?

**Comment by tgoldenberg** [comment]
@danleveille I ended up ditching this feature and going for just a regular scroll view without swiping for my app. You can get the demo to work with ScrollView - I just think it's a little complicated to optimize the performance and the situation described above. Good luck!

**Comment by danleveille** [comment]
@tgoldenberg Oh, I totally missed your solution above. Thanks! I ended up switching too -- using a snapping ScrollView and it kind of has the same feel.

**Comment by brentvatne** [comment]
Hi there!

What I did here was lock the `ScrollView` when I start an interaction and unlock it when I stop: https://github.com/exponentjs/react-native-for-curious-people/blob/master/Articles/IntroductionArticle.js#L124-L128
