### ISSUE TITLE
Memory Leak? 

### ISSUE THREAD

**Issue by thorbenandresen** [brentvatne/react-native-animated-demo-tinder#13]
Hi,

when I open this example, my memory usage increases with 1-2MB per second constantly, even without doing a single swipe. Swiping will increase the speed of the memory filling up. 

![screen_shot_2015-12-07_at_7_22_48_pm](https://cloud.githubusercontent.com/assets/8238976/11644752/f2e2e620-9d1c-11e5-9085-0c67b1e867fc.jpg)

How can i prevent this?

btw. I dont know if it is of any importance to this issue. but I added the changing line 75 on index.ios.js to 

```
          }).start(this._resetState.bind(this))
```

in order to get the example to work.

**Comment by browniefed** [comment]
Likely has nothing to do with the Animated API, likely due to the version of React Native that is being used. Various issues on react-native pertaining to small memory leaks.

**Comment by thorbenandresen** [comment]
@browniefed ok, thanks. Is there any work-around? I am working on an app with such a tinder-interface and I'd really like to prevent it from crashing after a couple of minutes. 

btw. I am using 0.16 for this example.

**Comment by browniefed** [comment]
https://github.com/facebook/react-native/issues/4538
