### ISSUE TITLE
Error on exponentjs with react-native 0.10

### ISSUE THREAD

**Issue by michaltaberski** [brentvatne/react-native-animated-demo-tinder#8]
Hi,

first of all thanks for the code sample. It's nice introduction to pan responder.

However I got a problem to get it working on exponentjs after I updated react-native to v0.10. 
I wonder if it's a problem of the code sample, or exponentjs itself. 

![photo 31 08 2015 10 58 26](https://cloud.githubusercontent.com/assets/202033/9575508/b342e356-4fd0-11e5-965e-948dc1228a53.png)

Do you have an idea where the problem could be?

**Comment by brentvatne** [comment]
t___t

weird, check this out for an example of it working in Exponent: https://github.com/exponentjs/react-native-for-curious-people/blob/master/ExampleComponents/TinderExample.js
